### ISSUE TITLE
Sign up grid

### ISSUE THREAD

**Issue by anggabard** [TeodorPloae/dave#2]
Trebuie refacut gridul. mie imi iese din pagina.
Grija mare si la Id-ul de la issue-ul anterior.
![screenshot from 2019-01-12 16-36-01](https://user-images.githubusercontent.com/22707482/51074468-4c1f6500-1688-11e9-8071-007162bb4049.png)

**Comment by TeodorPloae** [comment]
mie imi arata ok men
